# Generated by Django 2.2.14 on 2020-08-15 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200815_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='pub_date',
        ),
    ]
