# Generated by Django 2.2.14 on 2020-08-16 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0004_auto_20200815_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='votes_total',
        ),
        migrations.AddField(
            model_name='post',
            name='votes_total',
            field=models.ManyToManyField(default=1, related_name='Voted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('upvote', 'upvote'), ('downvote', 'downvote')], max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
