# Generated by Django 2.2.14 on 2020-08-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200816_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='votes_total',
        ),
        migrations.AddField(
            model_name='post',
            name='votes_total',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='upvote',
        ),
    ]
