# Generated by Django 2.2.14 on 2020-08-16 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0006_auto_20200816_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='votes_total',
        ),
        migrations.AddField(
            model_name='post',
            name='votes_total',
            field=models.ManyToManyField(blank=True, default=None, related_name='vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
